### ISSUE TITLE
What is the correct way to connect the database?

### ISSUE THREAD

**Issue by kpripper** [manshu/reactjs-chrome-extension#4]
Greetings! What is the correct database connection option in this boilerplate? Need a server? Are the options for creating a similar boilerplate based on Next Js being considered?

**Comment by manshu** [comment]
@kpripper You can use multiple ways to connect to DB. 
1. Firebase (Only where you've DOM available in Popup etc)
2. Use MERN stack and build a backend API and build an API.

No, NextJS isn't relevant in Chrome Ext
